<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.10.2 on linux)" generated="20220125 10:23:58.087" rpa="false" schemaversion="2">
<suite id="s1" name="Suites" source="/suites">
<suite id="s1-s1" name="Todo App" source="/suites/todo_app.robot">
<test id="s1-s1-t1" name="Get Request TestWebsite">
<kw name="Create Session And Assert" library="web_request_keywords">
<arg>http://localhost:3000</arg>
<arg>10</arg>
<arg>200</arg>
<kw name="Create Session" library="RequestsLibrary">
<arg>getwebsite</arg>
<arg>${site}</arg>
<arg>verify=false</arg>
<arg>max_retries=${max_retries}</arg>
<arg>backoff_factor=1</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20220125 10:23:58.239" level="INFO">Creating Session using : alias=getwebsite, url=http://localhost:3000, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20220125 10:23:58.238" endtime="20220125 10:23:58.240"/>
</kw>
<kw name="GET On Session" library="RequestsLibrary">
<var>${resp}</var>
<arg>getwebsite</arg>
<arg>/</arg>
<arg>${expected_status}</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<msg timestamp="20220125 10:24:00.344" level="WARN">Retrying (RetryAdapter(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759690&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:02.348" level="WARN">Retrying (RetryAdapter(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759870&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:06.354" level="WARN">Retrying (RetryAdapter(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf877599f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:14.364" level="WARN">Retrying (RetryAdapter(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759ba0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:14.407" level="INFO">GET Request : url=http://localhost:3000/?200 
 path_url=/?200 
 headers={'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
 body=None 
 </msg>
<msg timestamp="20220125 10:24:14.407" level="INFO">GET Response : url=http://localhost:3000/?200 
 status=200, reason=OK 
 headers={'X-Powered-By': 'Express', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 18 Mar 2021 17:53:24 GMT', 'ETag': 'W/"35a-17846787a20"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '858', 'Date': 'Tue, 25 Jan 2022 10:24:14 GMT', 'Connection': 'keep-alive', 'Keep-Alive': 'timeout=5'} 
 body=
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;meta charset="utf-8" /&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0, user-scalable=0" /&gt;
    &lt;link rel="stylesheet" href="css/bootstrap.min.css" crossorigin="anonymous" /&gt;
    &lt;link rel="stylesheet" href="css/font-awesome/all.min.css" crossorigin="anonymous" /&gt;
    &lt;link href="https://fonts.googleapis.com/css?family=Lato&amp;display=swap" rel="stylesheet" /&gt;
    &lt;link rel="stylesheet" href="css/styles.css" /&gt;
    &lt;title&gt;Todo App&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div id="root"&gt;&lt;/div&gt;
    &lt;script src="js/react.production.min.js"&gt;&lt;/script&gt;
    &lt;script src="js/react-dom.production.min.js"&gt;&lt;/script&gt;
    &lt;script src="js/react-bootstrap.js"&gt;&lt;/script&gt;
    &lt;script src="js/babel.min.js"&gt;&lt;/script&gt;
    &lt;script type="text/babel" src="js/app.js"&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
 
 </msg>
<msg timestamp="20220125 10:24:14.408" level="INFO">${resp} = &lt;Response [200]&gt;</msg>
<status status="PASS" starttime="20220125 10:23:58.240" endtime="20220125 10:24:14.408"/>
</kw>
<kw name="Should Be Equal As Strings" library="BuiltIn">
<arg>${resp.status_code}</arg>
<arg>${expected_status}</arg>
<doc>Fails if objects are unequal after converting them to strings.</doc>
<msg timestamp="20220125 10:24:14.409" level="INFO">Argument types are:
&lt;class 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" starttime="20220125 10:24:14.408" endtime="20220125 10:24:14.409"/>
</kw>
<status status="PASS" starttime="20220125 10:23:58.237" endtime="20220125 10:24:14.409"/>
</kw>
<status status="PASS" starttime="20220125 10:23:58.237" endtime="20220125 10:24:14.410"/>
</test>
<kw name="Delete All Sessions" library="RequestsLibrary" type="TEARDOWN">
<doc>Removes all the session objects</doc>
<msg timestamp="20220125 10:24:14.411" level="INFO">Deleting All Sessions</msg>
<status status="PASS" starttime="20220125 10:24:14.410" endtime="20220125 10:24:14.411"/>
</kw>
<status status="PASS" starttime="20220125 10:23:58.123" endtime="20220125 10:24:14.411"/>
</suite>
<status status="PASS" starttime="20220125 10:23:58.091" endtime="20220125 10:24:14.415"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Suites">Suites</stat>
<stat pass="1" fail="0" skip="0" id="s1-s1" name="Todo App">Suites.Todo App</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220125 10:24:00.344" level="WARN">Retrying (RetryAdapter(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759690&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:02.348" level="WARN">Retrying (RetryAdapter(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759870&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:06.354" level="WARN">Retrying (RetryAdapter(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf877599f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
<msg timestamp="20220125 10:24:14.364" level="WARN">Retrying (RetryAdapter(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7faf87759ba0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /?200</msg>
</errors>
</robot>
